name: ELK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy_elk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

  notify:
    runs-on: ubuntu-latest
    needs: deploy_elk
    steps:
      - name: Check if Workflow Succeeded or Failed
        id: check_status
        run: |
          if [[ ${{ needs.deploy_elk.result }} == 'success' ]]; then
            echo "status=success" >> $GITHUB_ENV
          else
            echo "status=failure" >> $GITHUB_ENV
          fi

      - name: Send Success Email Notification
        if: ${{ env.status == 'success' }}
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: 'recipient@example.com'
          from: 'sender@example.com'
          subject: 'CI/CD Pipeline Success Notification'
          body: |
            Workflow: ELK Deployment
            Triggered by: ${{ github.actor }}
            Repository: ${{ github.repository }}
            Status: SUCCESS 🎉
            All jobs passed successfully:
              - Elasticsearch Deployment: Success
              - Filebeat Deployment: Success
              - Kibana Deployment: Success
              - Logstash Configuration: Success
          secure: true

      - name: Send Failure Email Notification
        if: ${{ env.status == 'failure' }}
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: 'recipient@example.com'
          from: 'sender@example.com'
          subject: 'CI/CD Pipeline Failure Notification'
          body: |
            Workflow: ELK Deployment
            Triggered by: ${{ github.actor }}
            Repository: ${{ github.repository }}
            Status: FAILURE ❌
            Some jobs failed. Please check the pipeline for errors:
              - Elasticsearch Deployment: Failed
              - Filebeat Deployment: Failed
              - Kibana Deployment: Failed
              - Logstash Configuration: Failed
          secure: true
